[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]

git2       = "0.18"     # accès à libgit2
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow     = "1.0"

